index.html
Hello,
I saw that you were having an issue with the light/dark mode in your indext.html file, so I went ahead and fixed it for you! Feel free to take a look and merge my branch if you're happy with the changes.  
Take Care, 
DB
=> Add dark mode toggle to index.html

style.css
- Updated the css file to make the scroll bar look cool.
- Please review .
=> Created gradient scroll bar.

script.js
Uses local storage to keep track of dark/light mode. Dark/Light modes persist on refresh.
Closes #14
=> dark mode stays on refresh

script.js
Reverts NageshMandal/Engineering-Notes-Website#15
it is not working fix it
=> Revert "dark mode stays on refresh"

index.html, style.css
- Fixed Navbar error
- Changed Style in footer
- Added styles to newletter
- Added styles to links
- Added styles to profile contact
=> fixed navbar bug and added more styles in footer

branch/style.css
=> Update style.css of branch

style.css
Fixed the position of mic in mobile view from center to right as it was overlapping with the logo.
=> Fixed position of mic in mobile view

branch/CE.html, branch/ME.html, branch/cs.html, branch/ece.html, branch/ee.html, index.html
Footer Changed in all branches and it appears like this
Screenshot ->
=> Changed footer of all branches, applied same scrollbar styling as Index.html and fixed Typing Errors

app.js, index.html
#30 solved 
- say "open + dept name" to redirect to required page
=> Add voice recognition features

index.html, script.js, style.css
I have added return to top arrow
=> Return to top arrow

index.html, script.js, style.css
projects should be Projects in the nav
=> changed projects to Projects in the nav

branch/CE.html, branch/ME.html, branch/cs.html, branch/ece.html, branch/ee.html, index.html
hello @NageshMandal  sir i had make the icons in the footer working and attach links of your social sites to them and also change the telegram icon to youtube icon as I am unable to find your telegram channel .
=> links in the Icons of social sites in the footer is fixed

index.html
on clicking the address part it will open the location of the college in google map in another tab. on clicking the phone no. dialer will open you will be able to directly call from your pc/laptop with the linked phone. on clicking the email you will be able to mail directly from your device
=> Improved the footer section

style.css
#78 Proper alignment Explore Now Button on the Home Page
Resolved the issue of misaligned placement for the Explore Now button, effectively enhancing the User Interface to provide a more intuitive and visually pleasing experience.
=> Updated style.css by positioning the Explore Now button on the Home page

index.html, script.js, style.css
I fix the color issue that was prevailing when changing to dark mode.
Before:-
After:-
=> Fix the color changing issue

README.md
=> #159 Readme is updated with badges

.vscode/settings.json, index.html, style.css
From GSSOC'23 Contributer
✨ Added phone, location, and mail icons to the footer section. The new icons provide improved user experience and make it easier to find important contact information. Now, visitors can quickly access the phone number, physical address, and email address with just a glance. Great addition to enhance the overall usability of the website. 👍
if you find it helpful ,please label me under GSSOC'23
=> Added Phone Icon to the footer

style.css
removed the hover effect of changing size from footer section to make the UI cleaner improving user experience.
=> footer-links-section UI modified

branch/CE.html, branch/ME.html, branch/cs.html, branch/ece.html, branch/ee.html, branch/theme.js
Hello, I am  a GSSOC'23 Contributor.
Previously on clicking the moon icon on any of the branches page there was no change.
So I have linked one new theme.js script file in all the branches to implement the dark mode.
Its now working in all the branches.
=> Implemented dark mode in all Branches

branch/CE.html, branch/ME.html, branch/cs.html, branch/ece.html, branch/ee.html
#212 
Favicon added in Branches.
Issue has been solved sucessfully.
**Screenshot**
=> Branch favicon is updated

Gallary-section/index.html
It was written "Gallay", I corrected and a also added a link in header of the webpage.
=> Corrected a misspell, and added a link. [GSSoC'23]

index.html, script.js, style.css
resolved #314 
now we can see contributors list with help of GitHub API.
**before**
**now**
=> added contributors list to main homepage

Gallary-section/index.html
Footer has been added in project
=> footeradded

CONTRIBUTING.md
updated the CONTRIBUTING.md file and edited out some errors.
=> updated CONTRIBUTING.md. edited out some error.

about.css, about.html, index.html
Added the about page and linked to the homepage.
Closes #519 
Here is how to looks :
=> Added the about page and linked to the homepage. [GSSoC]

style.css
Hello!!!,
I have followed all the steps required before contribution. For first contribution, I have done changes in the style.css part, modified color, background color of the social media icons to make a good look for visitors. Please review my changes and approve it if you found it useful.
=> changes done in style.css for footer part

library.css
=> Library section made responsive (Photos attached) #471

Gallary-section/index.html, Gallary-section/style.css
Changed the style keeping in mind the actual style of cards in gallery section.
Closes #518 
Screenshot:
=> Changed the style keeping in mind the actual style of cards.

index.html, style.css
Please refer to the issue #533 
contact us element in the footer linked to contact us  page
and the envelope icon and email- id aligned in one line
=> Issue 533 solved 

README.md
As mentioned in #515 I have updated the contributors list in README.md
=> updated the contributors list in README.md

branch/style.css, style.css
i saw that your website could use a slight changes in the UI and responsiveness, that can bring huge difference, i have already made the changes i hope you will like these and Merge the Changes
|           Original           |           Updated           |
| :--------------------------: | :-------------------------: |
| ![](https://raw.githubusercontent.com/arpittyagirocks/Media/main/Engineering-Notes/before1.png) | ![link](https://raw.githubusercontent.com/arpittyagirocks/Media/main/Engineering-Notes/after1.png) |
| ![](https://raw.githubusercontent.com/arpittyagirocks/Media/main/Engineering-Notes/before2.png) | ![link](https://raw.githubusercontent.com/arpittyagirocks/Media/main/Engineering-Notes/after2.png) |
| ![](https://raw.githubusercontent.com/arpittyagirocks/Media/main/Engineering …
=> UI and responsiveness improvement

Gallary-section/index.html
=> Added the backtotop button in gallery

style.css
This PR resolve #710 and #689
Changes the text CSS in night mode and add cursor pointer to the submit project
Kindly mark this contribution in GSSOC-2023
=> change the text css and add cursor pointer to project submit

about.html
Issue-
Link the Contact Us Page in home and about us #707
Close #707
=> Added navigation to home and about us page

.vscode/settings.json, style.css
This PR fixed issue #755 
Close #755
=> Fixed logo orientation

about.html, contactus.css, contactus.html, index.html, library.html, placement.html, projects.html, style.css, syllabus.html
PR resolves #720
Updated the links to other pages, to navigate from contact page. Added home page nav item to avoid confusion, since there is no access to the main page from the top nav bar.
Kindly mark this under GSSoC'23
=> Updated contact us pages nav bar with links and also added home link

style.css
Issue #706 
Close #706 
Fixed the search button
Before
After
=> search button fixed

Gallary-section/index.html, Gallary-section/style.css, about.html, branch/CE.html, branch/ME.html, branch/cs.html, branch/ece.html, branch/ee.html, contact.html, contactus.css, contactus.html, library.css, library.html, placement.html, projects.html, syllabus.html
Make the navbar of all the pages similar to Home page #783
Close #783
=> Added the new navbar to all the sites

contactus.css, contactus.html
issue #831 
I made some change around placement of objects in contact US page 
Here is Updated Changes
=> Contact Us Page Updated

about.html, contact.html, contactus.html, event.css, event.html, index.html, library.html, placement.html, projects.html, style.css, syllabus.html
Fixes #799 
Description: This pull request adds the event section to the project, enhancing the functionality and user experience for managing and displaying events.
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
=> Add [feat(event)]: added event section in the project

index.html, style.css
Closes #684 
video reference:
[Screencast from 02-07-23 02:45:22 PM IST.webm](https://github.com/NageshMandal/Engineering-Notes-Website/assets/104543751/58c17bed-dde5-482e-b521-403205a87d6c)
=> faqs added

index.html, style.css
Resolve issue #806 
I have made some significant changes to UI/UX of the footer component
- Make transition on hovering contact button smooth
- Align all the divs inside the footer in one line
- Make cursor pointer when hovering over an email
- Make e-mail and call icons of the same colour rather than being different
- Add margin to youtube icon in socials
#New
=> Enhance footer

contactus.html
Added validation to all the inputs of the contact us form.
=> Contact us form validated

style.css
#1026 issue resolve
https://github.com/NageshMandal/Engineering-Notes-Website/assets/92370893/1753c970-bc9e-405d-8021-239546e32005
kindly add this as GSSOC Contribution
=> adding 3d animation in the student image #1026

README.md
Closes #977
The Licenses Section has been updated. It looks more professional now.
=> Added the MIT License badge and changed the license section 

Gallary-section/index.html, about.html, contact.html, contactus.html, event.html, index.html, library.html, placement.html, projects.html, script.js, syllabus.html
Issue #906 
This pull request introduces an AI Chat and Voice Assistant to the Web3 Expense Tracker website, enhancing the user experience by providing support for Frequently Asked Questions (FAQ), page navigation, and overall user interaction.
1. Integrated an AI Chat and Voice Assistant feature using a suitable library or API to provide interactive support to users visiting the college website.
2. Added necessary JavaScript code to initialize and handle the AI Chat and Voice Assistant on relevant pages.
3. Designed a chat interface that allows users to interact with the AI Assistant and receive instant responses to their queries.
4. This assistant  to address common user queries and provide instant responses using the AI Assistant.
5. Configured the AI Assistant to handle user queries …
=> Adding AI Chat and Voice Assistant for FAQ, Navigation, and User Experience Improvement

Gallary-section/index.html, Gallary-section/style.css, about.css, contactus.css, style.css, syllabus.css, syllabus.html
Title: Sticky Navbar Feature Request #1054 
Description:
Hello @NageshMandal ,
I hope you are doing well. As part of my contribution to GSSOC 23, I have implemented the "Sticky Navbar" feature for the website.
=> added changes for sticky nav bar

Gallary-section/index.html
ISSUE #1041 
CLOSE #1041 
hello ,
I am success to adding events section in the navbar in gallery section . please checked it and merge it .
=> fix: adding event section  in the navbar in gallery section #1041
